# Generated by Django 5.1b1 on 2024-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
